stages:
  prepare:
    cmd: python src/data/preprocessing.py
    deps:
    - assets/data/raw
    - src/data/preprocessing.py
    outs:
    - assets/data/processed
  train:
    cmd: python src/train.py
    deps:
    - assets/data/processed
    - src/train.py
    outs:
    - assets/models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - assets/models
    - src/evaluate.py
