stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
    - assets/data/raw
    - src/preprocessing.py
    outs:
    - assets/data/processed/test.tsv
    - assets/data/processed/train.tsv
    - assets/data/processed/validation.tsv
