stages:
  prepare:
    cmd: python src/data/preprocessing.py
    deps:
    - assets/data/raw
    - src/data/preprocessing.py
    outs:
    - assets/data/processed
  train:
    cmd: python src/train.py
    deps:
    - assets/data/processed
    - src/train.py
    outs:
    - assets/models
    - assets/outputs
  evaluate:
    cmd: python src/model/evaluate.py
    deps:
    - assets/models
    - assets/outputs
    - src/model/evaluate.py
    metrics:
    - assets/metrics/bag-of-words_metrics.json:
        cache: false
    - assets/metrics/tf-idf_metrics.json:
        cache: false
