stages:
  prepare:
    cmd: python src/remla/data/prep_rocessing.py
    deps:
    - assets/data/raw
    - src/remla/data/pre_processing.py
    outs:
    - assets/data/processed
  train:
    cmd: python src/remla/train.py
    deps:
    - assets/data/processed
    - src/remla/train.py
    outs:
    - assets/models
  evaluate:
    cmd: python src/remla/evaluate.py
    deps:
    - assets/models
    - src/remla/evaluate.py
