stages:
  validate:
    cmd: python src/remla/data/validate_schema.py
    deps:
      - assets/data/raw
      - src/remla/data/validate_schema.py
  prepare:
    cmd: python src/remla/data/pre_processing.py
    deps:
    - assets/data/raw
    - src/remla/data/pre_processing.py
    outs:
    - assets/data/processed
  train:
    foreach: ${models}
    do:
      cmd: python src/remla/train.py --module-name="remla.models.${item.module}" --model-name="${item.class}"
      deps:
      - assets/data/processed/train.tsv
      - src/remla/train.py
      - src/remla/models/${item.module}.py
      params:
        - models
      outs:
      - assets/models/${item.class}.joblib
  evaluate:
    foreach: ${models}
    do:
      cmd: python src/remla/evaluate.py --joblib-file-path="assets/models/${item.class}.joblib"
      deps:
      - assets/data/processed/validation.tsv
      - src/remla/evaluate.py
      - assets/models/${item.class}.joblib
      params:
        - models
