# Module key is relative with respect to src/remla/models directory

models:
  - module: bag_model
    class: BagModel
    config: bag_model_config
  - module: tfidf_model
    class: TfIdfModel
    config: tfidf_model_config
  - module: bert_model
    class: BertBasedModel
    config: bert_model_config