apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: remla
  namespace: remla
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: remla
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80