name: Test using pytest

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.12

    - name: Install (Development) Dependencies
      run: |
        pip install -e .
        
    - name: Run tests using pytest
      run: |
        pytest
