name: Check security issues using Bandit

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/security-check.yml
    branches: [ main ]
  pull_request:
    paths:
      - "**.py"
      - .github/workflows/security-check.yml
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  lint-ds:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.12

    - name: Install Bandit
      run: |
        pip install bandit
        
    - name: Check security issues using Bandit
      run: |
        bandit .
