name: tests

on:
  [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install main dependencies
      run: 
        pip install -r requirements.txt

    - name: Install test dependencies
      run: 
        pip install flake8 pytest pytest-cov

    - name: Build coverage file
      run:
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml